# Create a secert for aws marketplace
{{- if .Values.aws.awsMarketplace }}
apiVersion: v1
kind: Secret
metadata:
  namespace: kube-system
  name: px-aws-secret
type: Opaque
stringData:
  product-id: {{ template "px.getProductID" .}}
{{- end }}
---
# create a secret to store aws access key credentials 
{{- if .Values.aws.awsAccessKeyId}}
apiVersion: v1
kind: Secret
metadata:
  namespace: kube-system
  name: px-aws-credentials
type: Opaque
stringData:
 awsAccessKeyId : {{ .Values.aws.awsAccessKeyId }}
 awsSecretAccessKey : {{ .Values.aws.awsSecretAccessKey }}
{{- end }}