# Create a secert for aws marketplace
{{- if .Values.aws.marketplace }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ template "px.getDeploymentNamespace" . }}
  name: px-aws-secret
type: Opaque
stringData:
  product-id: {{ template "px.getProductID" .}}
{{- end }}
---
# create a secret to store aws access key credentials
{{- $awsAccessKey := .Values.aws.accessKeyId | default "none" }}
{{- $awsSecretKey := .Values.aws.secretAccessKey | default "none" }} 
{{- if and ( not (eq $awsAccessKey "none")) ( not (eq $awsSecretKey "none"))}}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ template "px.getDeploymentNamespace" . }}
  name: px-aws-credentials
type: Opaque
stringData:
 awsAccessKeyId : {{ $awsAccessKey }}
 awsSecretAccessKey : {{ $awsSecretKey }}
{{- end }}