apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-predelete-configmap
  namespace: {{ template "px.getDeploymentNamespace" . }}
data:
  deletePatch.sh: |-
{{ .Files.Get "scripts/deletePatch.sh" | indent 4}}