{{- if .Values.deployCluster }}
{{- $customRegistryURL := .Values.customRegistryURL | default "none" }}
{{- $registrySecret := .Values.registrySecret | default "none" }}
{{- $clusterName := .Values.clusterName }}
{{- $deleteType := .Values.deleteType | default "UninstallAndWipe" }}

apiVersion: batch/v1
kind: Job
metadata:
  namespace: kube-system
  name: px-hook-delete-storagecluster
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    app.kubernetes.io/managed-by: {{.Release.Service | quote }}
    app.kubernetes.io/instance: {{.Release.Name | quote }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 0
  template:
    spec:
      {{- if not (eq $registrySecret "none") }}
      imagePullSecrets:
        - name: {{ $registrySecret }}
      {{- end }}
      serviceAccountName: {{ template "px.hookServiceAccount" . }}
      restartPolicy: Never
      containers:
        - name: delete-storagecluster
          {{- if eq $customRegistryURL "none" }}
          image: "bitnami/kubectl:{{ template "px.kubectlImageTag" . }}"
          {{- else}}
          image: "{{ $customRegistryURL }}/bitnami/kubectl:{{ template "px.kubectlImageTag" . }}"
          {{- end}}
          command: ['/bin/sh',
                    '-c',
                    '/opt/scripts/deletePatch.sh {{ $clusterName }} {{ $deleteType}} && kubectl -n kube-system delete storagecluster {{ $clusterName }} --ignore-not-found']
          volumeMounts:
          - name: config-volume-pre-delete
            mountPath: /opt/scripts
      volumes:
        - name: config-volume-pre-delete
          configMap:
            name: {{ .Release.Name }}-predelete-configmap
            defaultMode: 0777

{{- end }}


