name: portworx
version: "2.13.5"
appVersion: 2.13.5
description: A Helm chart for installing Portworx on Kubernetes.
tillerversion: ">=2.9.0"
apiVersion: v1
home: https://portworx.com/
sources:
  - https://github.com/portworx/helm
icon: https://raw.githubusercontent.com/portworx/helm/master/doc/media/px-logo.png
