name: portworx
version: "3.0.0"
appVersion: 3.0.0
description: A Helm chart for installing Portworx on Kubernetes.
tillerversion: ">=2.9.0"
apiVersion: v1
home: https://portworx.com/
sources:
  - https://github.com/portworx/helm
icon: https://raw.githubusercontent.com/portworx/helm/master/doc/media/px-logo.png
